// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svvunmtfkalnedeacmjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dnVubXRma2FsbmVkZWFjbWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDA5MDUsImV4cCI6MjA3MDIxNjkwNX0.70dhegOVT5KyglQpq3eq-lUr0StxN1T9jT42l3h15qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});